### PR TITLE
Fix for my previous commit.

### PR DESCRIPTION
**Pull request by lig**
https://github.com/stephrdev/django-mongoforms/commit/c55f9db87747c22e8ebdb07812e741481c43312a was incorrect.

Fixed now.

### CODE REVIEW

**Comment by stephrdev** [comment]
Are you sure, this will work now?

**Comment by lig** [comment]
Sorry, for that. I've tested it now. I've missed that form didn't completely update another time, just checked that there is no exception. It does update now.

I just don't very like that it uses "_query" directly. Think that it is time to have some unittests in this library...

**Comment by hensom** [comment]
I believe this patch has an issue in that it ignores the value that was passed to clean(). This case cause issues with the following construction:

class Sample(Document):
  pass

class SampleChoiceForm(Form):
   sample = ReferenceField(Sample.objects)

Since filtering a mongoengine queryset doesn't return a new queryset, but rather modifies the existing queryset in place the base queryset should actually be deepcopied before calling get(id=oid). This will ensure that you don't receive a duplicate id filter exception, but also that you don't return the incorrect document as is the current behaviour.

**Comment by lig** [comment]
Thank you hensom! Now i've got some clues. Will fix it later.

**Comment by lig** [comment]
Just one thing to mention. This commit https://github.com/stephrdev/django-mongoforms/commit/c55f9db87747c22e8ebdb07812e741481c43312a causing things to not work at all. As the form will work only once since module was loaded.

**Comment by stephrdev** [comment]
I reverted the changes.

**Comment by lig** [comment]
Another thing to Hensom. I believe you are right about the way mongoengine does queryset processing and i will test your code sample. Anyway i do not think you are right with "this patch ignores the value that was passed to clean()" as it leaves this codeline unchanged:

```
oid = super(ReferenceField, self).clean(oid)
```

https://github.com/lig/django-mongoforms/commit/b78c2a81551fd0a24415e0c38eb1cc2297df70a2#L0R35

Just to let you know. This code seems to work for this form class https://github.com/lig/picket/blob/master/apps/picket/admin/forms.py#L35 for this document https://github.com/lig/picket/blob/master/apps/picket/documents.py#L68

**Comment by hensom** [comment]
The actual line that ignores the value is here:
https://github.com/lig/django-mongoforms/commit/b78c2a81551fd0a24415e0c38eb1cc2297df70a2#L0L37

```
if 'id' in self.queryset._query_obj.query:
  obj = self.queryset.get()
```

In this case the (possibly new) value that oid has will not matter as it will take a previous queryset which will reference the previous OID. You can see this sort of behaviour is you run the test:
  https://gist.github.com/794122

The test creates 3 objects and two sets of forms for each. One for will use a shared query set, while the other will create a new one when the form is initialized. If you run it with the stock ReferenceField you will notice that both forms will validate for the first object, but thereafter only one of the forms will validate. If you replace you version of ReferenceField with this one https://gist.github.com/794129 you will be able to validate both forms, but you will see that the form that uses the shared queryset instance will always return the same object even though different input was passed.

I'm currently using the following patch to alleviate both of these issues:
  https://gist.github.com/794134

I haven't done any significant testing against it and I think it should be refactored to use to_python instead of clean as I suspect that the chained call to ChoiceField's clean method would actually loop through the entire queryset by default.

**Comment by lig** [comment]
> I'm currently using the following patch to alleviate both of these issues:
> https://gist.github.com/794134

This will not work in some cases.

That's why i have this patch.
https://github.com/lig/django-mongoforms/commit/b78c2a81551fd0a24415e0c38eb1cc2297df70a2

Well it looks like we are talking about the same.

Stephan, it seems to me that my last code will work. As i've tested it manually enough to be sure about that. 

But i will provide tests in next couple of days to be completely sure that this code works fine as the logic provided by it is critical to the whole project.

**Comment by hensom** [comment]
Ah, yes I see now that I wasn't capturing enough of the innards of the queryset when I made my prior patch. It seems the best course of action would be to have some way of copying the entire queryset as is. I need this sort of functionality for another project I'm working on, so I've implemented it in my own fork. I've an open pull request for it, but perhaps the base code might be of use here:

  https://github.com/hmarr/mongoengine/pull/130

**Pull request closed without merging**
