### PR TITLE
ListField and DictField

### PR DESCRIPTION
**Pull request by darvin**
We wrote working widgets and form fields for ListField and DictField.
Some documentation needed and may be some example in BlogApp.
Widgets needs jQuery for work, I don't think this may be a problem, 'cause last Django admin needs jQuery for work

### CODE REVIEW

**Comment by haridas** [comment]
I integrated the ListField with my application. It's working pretty well. Now I'm trying to find a way to figure out GenericReference Field UI.

Thank you.

**Comment by lig** [comment]
will look on this. going to test it before merging.

**Comment by lig** [comment]
@darvin could you please rebase your pull request on current master and provide some tests using templates that we have now.

**Comment by lig** [comment]
I'm not going to allow any client side dependencies such as jQuery.

**Comment by darvin** [comment]
I not gonna work on this code anymore, I drop project related to it a year ago

**Comment by lig** [comment]
ok. closing this as i've already started implementing these fields using more common approach.

**Pull request closed without merging**
